### ISSUE TITLE
Add IOs to `MceStartStop`

### ISSUE THREAD

**Issue by yeu-rioual** [YaskawaEurope/mlx-examples#48]
In order to make integration of `MceStartStop` easier, I propose to add new IOs:
- Add a new `bSystemHeld` output when the controller is in Held state (`nSmStartStop := 40`)
- Add a new `bHold` input to hold the trajectory. It would replace the `bStart` input action when `bSystemReady` is `True`. So the `bStart` input will only enable the servos or resume a trajectory

**Comment by yeu-rioual** [comment]
Adding `bSystemHeld` implies that `bStartIndicator` logic must be modified.

I would like to use this opportunity to remove the blinking on `bStartIndicator` and `bStopIndicator`.
If an upper-layer state machine needs to get `MceStartStop` status, blinking signals is not convenient.

For now, blinking is used for state transition (like holding, resuming, enabling servos,...).
But for most application, the user only need to know the RC status (stopped, ready or held).
So 3 status bits could be used:

- `bSystemReady`
- `bSystemStopped`
- `bSystemHeld`

Below the proposed modifications:

- `bSystemReady := TRUE` in states 30, 35, 40, 45, 50 or 60
- Replace `bStopIndicator` by `bSystemStopped`
- `bSystemStopped := TRUE` in states 0, 1 or 70
- `bSystemHeld` in state 40
- Remove `bStartIndicator`

**Comment by yeu-degroot** [comment]
Good idea.
This will introduce a third (optional) button on the HMI:

| `bStop` | `bHold` | `bStart` |

I like the idea, but would suggest to tie the restart functionality to that new button as well (no longer tied to `bStart`). How about renaming it to `bHoldRestart`:

| `bStop` | `bHoldRestart` | `bStart` |

**Comment by yeu-degroot** [comment]
As this a breaking change, I would propose to also do some renaming (for consistency + better fitting the situation):

- `bSystemReady` -> `bServoOn`
- `bSystemStopped` -> `bIdle`
- `bSystemHeld` -> `bHoldActive`
